apiVersion: apps/v1
kind: Deployment

metadata:
  name: atlas-board

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: atlas-board

  template:
    metadata:
      labels:
        app: atlas-board

    spec:
      containers:
        - name: atlas-board

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}