name: Helm Chart Validation and Push

on:
  push:
    branches:
      - main

    paths:
      - 'helm/**'
  
  workflow_dispatch:

permissions:
  contents: read

jobs:

  helm:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Verify Helm Installation
        run: helm version

      - name: Package Helm Chart
        run: |
          helm package helm/atlas-board

      - name: Get Packaged Chart Name
        run: |
          CHART_PACKAGE=$(ls *.tgz)
          echo "CHART_PACKAGE=$CHART_PACKAGE" >> $GITHUB_ENV

      - name: Login To DockerHub OCI Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | helm registry login registry-1.docker.io \
          --username "${{ secrets.DOCKER_USERNAME }}" \
          --password-stdin

      - name: Push Helm Chart To DockerHub
        run: |
          helm push $CHART_PACKAGE oci://registry-1.docker.io/shivawmm1810